import React from "react";

function studentsData() {
  return (
    <div>
      <section className="container">
        <div className="text">
          <h2>Students Data</h2>
          <p>
            This is my first website created during my time in PWC learning
            Software development
          </p>
        </div>

        <table id="customers">
          <thead>
            <tr>
              <th>First Name</th>
              <th>Second Name</th>
              <th>My Favorite Programming Language</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Oluwaseun</td>
              <td>Victor</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>James</td>
              <td>Oluwaseun</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>Oluwaseun</td>
              <td>Victor</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>James</td>
              <td>Oluwaseun</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>Oluwaseun</td>
              <td>Victor</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>James</td>
              <td>Oluwaseun</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>Oluwaseun</td>
              <td>Victor</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>James</td>
              <td>Oluwaseun</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>Oluwaseun</td>
              <td>Victor</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>James</td>
              <td>Oluwaseun</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>Oluwaseun</td>
              <td>Victor</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>James</td>
              <td>Oluwaseun</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>Oluwaseun</td>
              <td>Victor</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>James</td>
              <td>Oluwaseun</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>Oluwaseun</td>
              <td>Victor</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>James</td>
              <td>Oluwaseun</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>Oluwaseun</td>
              <td>Victor</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>James</td>
              <td>Oluwaseun</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>Oluwaseun</td>
              <td>Victor</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>James</td>
              <td>Oluwaseun</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>Oluwaseun</td>
              <td>Victor</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>James</td>
              <td>Oluwaseun</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>Oluwaseun</td>
              <td>Victor</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>James</td>
              <td>Oluwaseun</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>Oluwaseun</td>
              <td>Victor</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>James</td>
              <td>Oluwaseun</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>Oluwaseun</td>
              <td>Victor</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>James</td>
              <td>Oluwaseun</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>Oluwaseun</td>
              <td>Victor</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>James</td>
              <td>Oluwaseun</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>Oluwaseun</td>
              <td>Victor</td>
              <td>JavaScript</td>
            </tr>
            <tr>
              <td>James</td>
              <td>Oluwaseun</td>
              <td>JavaScript</td>
            </tr>
          </tbody>
        </table>
      </section>
    </div>
  );
}

export default studentsData;
