name: First WorkFlow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
      - name: Multi Line
        run: |
          echo first line > multiline.txt
          echo second line >> multiline.txt
          echo thrid line >> multiline.txt
          cat multiline.txt
